contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: b7f8dfe3-c472-4a1b-88b5-0d2f438af76b
inputs: []
name: test-rajesh_copy
outputs: []
sourceplaybookid: 0a474e22-2c18-4d21-8fa5-70a6c8c36670
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 98b58bb6-b66f-4cc0-8ba4-c4d976a86a94
      iscommand: false
      name: ""
      version: -1
    taskid: 98b58bb6-b66f-4cc0-8ba4-c4d976a86a94
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello World
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8958cce2-cd16-4aa8-87b5-3e39fbbf855d
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 8958cce2-cd16-4aa8-87b5-3e39fbbf855d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8cf59a6f-44c7-4b30-81ac-939d1240f275
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 8cf59a6f-44c7-4b30-81ac-939d1240f275
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 450
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 465,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
